name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
template: |
  $CHANGES
categories:
  - title: "🚀 Features"
    labels:
      - enhancement
  - title: "🐛 Bug Fixes"
    labels:
      - bug
  - title: "🧹 Chores"
    labels:
      - chore
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "* No changes"
autolabeler:
  - label: feature
    title:
      - "/^feat/"
  - label: bug
    title:
      - "/^fix/"
  - label: chore
    title:
      - "/^chore/"
